### ISSUE TITLE
Checks are bound to other workflow

### ISSUE THREAD

**Issue by Skillkiller** [LouisBrunner/checks-action#49]
Hello,
I have the workflow ``Check pr requirements`` which creates 2 checks using this action and stores the corresponding status. In parallel to this workflow, the ``Test project`` workflow is executed at the PR opening which does not use this action. In the PR overview, the two checks from ``Check pr requirements`` appear in the workflow ``Test project``.

PR status:
![grafik](https://user-images.githubusercontent.com/18444809/226502457-b7ecd681-5d94-421e-a1c8-4a47ffea3c44.png)

Check pr requirements:
![grafik](https://user-images.githubusercontent.com/18444809/226502533-cd7747b2-dec9-45bd-a9b6-0b296f2abaf6.png)

**Comment by LouisBrunner** [comment]
Hey @Skillkiller,

It seems like this issue is related to this one: #26 

Someone posted a potential workaround (https://github.com/LouisBrunner/checks-action/issues/26#issuecomment-1232948025) to ensure the checks are associated with the right workflow, apart from this, I am not sure anything can be done on our end.

**Comment by Skillkiller** [comment]
Hello @LouisBrunner,

thanks for the reference. I had not found this issue earlier. I will use the linked [workaround](https://github.com/LouisBrunner/checks-action/issues/26#issuecomment-1232948025) and therefore close my issue as well. Thanks for your help.
